### ISSUE TITLE
getting points with label searching

### ISSUE THREAD

**Issue by kashikhan1** [arjunmehta/node-georedis#23] opened 2017-05-10 11:31 UTC
var locationSet = {
  'Toronto': {latitude: 43.6667, longitude: -79.4167,label:"a"},
  'Philadelphia': {latitude: 39.9523, longitude: -75.1638,label:"b"},
  'Palo Alto': {latitude: 37.4688, longitude: -122.1411,label:"c"},
  'San Francisco': {latitude: 37.7691, longitude: -122.4449,label:"b"},
  'St. John\'s': {latitude: 47.5500, longitude: -52.6667,label:"a"},
  'New York': {latitude: 40.7143, longitude: -74.0060,label:"b"},
  'Twillingate': {latitude: 49.6500, longitude: -54.7500,label:"a"},
  'Ottawa': {latitude: 45.4167, longitude: -75.7000,label:"b"},
  'Calgary': {latitude: 51.0833, longitude: -114.0833,label:"a"},
  'Mumbai': {latitude: 18.9750, longitude: 72.8258,label:"c"}
}
geo.nearby('Toronto',50000000, options,function(err, locations){
  if(err) console.error(err)
   else console.log('nearby locations:', locations); 
}); 

i want to get nearby with respect label,

**Comment by arjunmehta** [comment] 2017-05-10 13:30
@kashikhan1 This seems like a duplicate of https://github.com/arjunmehta/node-georedis/issues/20
Closing in favour of that issue.

**Closed by arjunmehta** 2017-05-10 13:30 UTC
